#################################################################################
# Start of configuration file
#################################################################################

# Directory where Logs are placed
LOG_DIR : "./logs/"
LOG_FILE : "./logs//smile_trace_log.txt"
##############################################################################################
# Server and repository
##############################################################################################
# Server where graph is stored
SERVER_URL : "http://localhost:7200"
# Repository where graph is stored
REPOSITORY : 'smile_unit_test'
# named graph where triples are stored, None if default graph
GRAPH_NAME : "http://smile"
# What is the run label used for this mapping?
RUN_LABEL : 'TEST_1'

# Default Namespace
NM : "http://smile/#"
PREFIX : 'smile'

DB_INDEX_FIELDS: []